export const SUBMIT_LOGIN_DATA = 'SUBMIT_LOGIN_DATA';

export const SUBMIT_EXPENSES_DATA = 'SUBMIT_EXPENSES_DATA';

export const REQUEST_API = 'REQUEST_API';
export const GET_API_SUCCESS = 'REQUEST_API_SUCCESS';
export const GET_API_ERROR = 'REQUEST_API_ERROR';
